{
    'name': "Odoo Ecommerce",
    'version': '12.0.1.0.0',
    'category':'Extra Tools',
    'summary':'Module for E-Commerce',
    # 'sequence':'AGPL-3',
    'author':'Stack Summation',
    'maintainer':'Stack Summation',
    'website':'https://www.google.com/',
    'depends':['sale'],
    'demo':[],
    'data':[
        'wizards/create_order.xml',
        'views/client.xml',
        'views/order.xml',
        'views/product.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/sequence.xml',
        'reports/reports.xml',
        'reports/client_card.xml'
    ],
    'installable':True,
    'application':True,
    'auto_install':False,
}
